"""Demo member records for populating a development database.

These are FICTIONAL people, not real SGN members. Every address is on
example.com (a reserved domain that cannot receive mail) so this data can
never be confused for the real membership list or accidentally emailed.

The mix is deliberate rather than random, so the directory, admin panel and
tier gating all have something realistic to exercise:

  - all three tiers, weighted towards Basic as the real funnel is
  - every entry in MEMBER_CATEGORIES and a broad spread of INDUSTRIES
  - a few members pending admin review (active=False)
  - a mix of is_searchable, since the directory is opt-in and reciprocal

`industries` and `categories` values must match app/core/industries.py and
app/core/categories.py; the seeder normalises them and will fail loudly on a
typo rather than silently writing an unrecognised label.
"""

SEED_MEMBERS: list[dict] = [
    {
        "first_name": "Noura",
        "last_name": "Al-Rashid",
        "email": "noura.alrashid@example.com",
        "company": "Tharwa Ventures",
        "industries": ["Venture Capital & Private Equity", "Technology & Software"],
        "categories": ["Investor", "Professional"],
        "interests": "Early-stage SaaS, UK-Saudi market entry, founder diligence",
        "phone": "+966 50 123 4567",
        "bio": (
            "Principal at a Riyadh-based venture fund investing in early-stage software "
            "across the Gulf. Previously a growth operator in London."
        ),
        "linkedin": "https://www.linkedin.com/in/example-noura-alrashid",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "James",
        "last_name": "Whitfield",
        "email": "james.whitfield@example.com",
        "company": "Meridian Energy Partners",
        "industries": ["Renewable Energy", "Hydrogen & Clean Fuels"],
        "categories": ["Company Owner", "Entrepreneur"],
        "interests": "Green hydrogen offtake, project finance, NEOM supply chains",
        "phone": "+44 7700 900123",
        "bio": (
            "Founder of a UK developer building green hydrogen projects, currently "
            "exploring Saudi joint ventures."
        ),
        "linkedin": "https://www.linkedin.com/in/example-james-whitfield",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Layla",
        "last_name": "Haddad",
        "email": "layla.haddad@example.com",
        "company": "Imperial College London",
        "industries": ["Research & Academia", "Biotechnology"],
        "categories": ["Professional", "Student"],
        "interests": "Translational biotech, spin-out formation, research commercialisation",
        "phone": "+44 7700 900456",
        "bio": (
            "PhD researcher in synthetic biology, working on routes from academic "
            "research to commercial therapeutics."
        ),
        "linkedin": "https://www.linkedin.com/in/example-layla-haddad",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Abdulaziz",
        "last_name": "Al-Otaibi",
        "email": "abdulaziz.alotaibi@example.com",
        "company": "Najd Capital",
        "industries": ["Investment & Asset Management", "Real Estate & Development"],
        "categories": ["Investor"],
        "interests": "Giga-project real estate, institutional allocation, co-investment",
        "phone": "+966 55 987 6543",
        "bio": "Asset manager covering Saudi real estate and infrastructure allocations.",
        "linkedin": "https://www.linkedin.com/in/example-abdulaziz-alotaibi",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Sophie",
        "last_name": "Brennan",
        "email": "sophie.brennan@example.com",
        "company": "Kestrel AI",
        "industries": ["Artificial Intelligence & Data", "Technology & Software"],
        "categories": ["Entrepreneur", "Company Owner"],
        "interests": "Applied ML, enterprise AI adoption, Gulf distribution partners",
        "phone": "+44 7700 900789",
        "bio": (
            "Co-founder and CTO of an applied AI company serving enterprise clients in "
            "the UK and expanding into the GCC."
        ),
        "linkedin": "https://www.linkedin.com/in/example-sophie-brennan",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Faisal",
        "last_name": "Al-Harbi",
        "email": "faisal.alharbi@example.com",
        "company": "Saudi Aramco",
        "industries": ["Oil & Gas", "Environment & Sustainability"],
        "categories": ["Professional"],
        "interests": "Energy transition strategy, carbon capture, industrial decarbonisation",
        "phone": "+966 53 222 1188",
        "bio": "Strategy lead working on decarbonisation pathways for heavy industry.",
        "linkedin": "https://www.linkedin.com/in/example-faisal-alharbi",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Hannah",
        "last_name": "Okafor",
        "email": "hannah.okafor@example.com",
        "company": "Lowell & Crane",
        "industries": ["Legal Services", "Banking & Financial Services"],
        "categories": ["Professional"],
        "interests": "Cross-border M&A, joint venture structuring, regulatory navigation",
        "phone": "+44 7700 900234",
        "bio": (
            "Corporate lawyer advising on UK-Gulf transactions, with a focus on joint "
            "ventures and market entry structures."
        ),
        "linkedin": "https://www.linkedin.com/in/example-hannah-okafor",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Omar",
        "last_name": "Bin Salem",
        "email": "omar.binsalem@example.com",
        "company": "Mudun Logistics",
        "industries": ["Logistics & Supply Chain", "Maritime & Ports"],
        "categories": ["Company Owner"],
        "interests": "Red Sea trade routes, port digitisation, freight technology",
        "phone": "+966 56 444 3322",
        "bio": "Runs a regional logistics operator focused on Red Sea and Gulf corridors.",
        "linkedin": "https://www.linkedin.com/in/example-omar-binsalem",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Charlotte",
        "last_name": "Dunn",
        "email": "charlotte.dunn@example.com",
        "company": "Northgate Life Sciences",
        "industries": ["Pharmaceuticals", "Medical Devices"],
        "categories": ["Professional", "Investor"],
        "interests": "Clinical trial partnerships, medtech regulation, health localisation",
        "phone": "+44 7700 900567",
        "bio": (
            "Commercial director in life sciences, building clinical and distribution "
            "partnerships across the Middle East."
        ),
        "linkedin": "https://www.linkedin.com/in/example-charlotte-dunn",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Khalid",
        "last_name": "Al-Mutairi",
        "email": "khalid.almutairi@example.com",
        "company": "Sahab Fintech",
        "industries": ["Fintech", "Islamic Finance"],
        "categories": ["Entrepreneur", "Company Owner"],
        "interests": "Shariah-compliant products, payments infrastructure, SAMA licensing",
        "phone": "+966 50 777 8899",
        "bio": "Founder of a Saudi fintech building Shariah-compliant lending products.",
        "linkedin": "https://www.linkedin.com/in/example-khalid-almutairi",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Eleanor",
        "last_name": "Vance",
        "email": "eleanor.vance@example.com",
        "company": "Vance Advisory",
        "industries": ["Consulting & Professional Services", "Government & Public Sector"],
        "categories": ["Company Owner", "Professional"],
        "interests": "Public sector transformation, Vision 2030 programmes, policy design",
        "phone": "+44 7700 900890",
        "bio": (
            "Independent adviser to government and quasi-government bodies on large "
            "transformation programmes."
        ),
        "linkedin": "https://www.linkedin.com/in/example-eleanor-vance",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Yousef",
        "last_name": "Al-Dosari",
        "email": "yousef.aldosari@example.com",
        "company": "Qimam Studios",
        "industries": ["Gaming & Esports", "Entertainment & Leisure"],
        "categories": ["Entrepreneur"],
        "interests": "Games publishing, esports infrastructure, Savvy ecosystem",
        "phone": "+966 54 321 9876",
        "bio": "Building a games studio in Riyadh with an eye on international publishing.",
        "linkedin": "https://www.linkedin.com/in/example-yousef-aldosari",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Priya",
        "last_name": "Raman",
        "email": "priya.raman@example.com",
        "company": "Helix Digital Health",
        "industries": ["Digital Health", "Healthcare Services"],
        "categories": ["Entrepreneur", "Company Owner"],
        "interests": "Remote care delivery, health data interoperability, MOH procurement",
        "phone": "+44 7700 900345",
        "bio": "Founder of a digital health platform working with NHS and Gulf providers.",
        "linkedin": "https://www.linkedin.com/in/example-priya-raman",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Bandar",
        "last_name": "Al-Qahtani",
        "email": "bandar.alqahtani@example.com",
        "company": "Ministry of Investment",
        "industries": ["Government & Public Sector", "Investment & Asset Management"],
        "categories": ["Professional"],
        "interests": "Inbound investment, licensing pathways, investor aftercare",
        "phone": "+966 59 111 2233",
        "bio": "Works on inbound investment facilitation for international companies.",
        "linkedin": "https://www.linkedin.com/in/example-bandar-alqahtani",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": False,
    },
    {
        "first_name": "Thomas",
        "last_name": "Ashworth",
        "email": "thomas.ashworth@example.com",
        "company": "Ashworth Robotics",
        "industries": ["Manufacturing & Industrial", "Semiconductors & Hardware"],
        "categories": ["Company Owner", "Entrepreneur"],
        "interests": "Industrial automation, localisation requirements, NIDLP",
        "phone": "+44 7700 900678",
        "bio": "Builds industrial robotics systems, exploring Saudi manufacturing localisation.",
        "linkedin": "https://www.linkedin.com/in/example-thomas-ashworth",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Reem",
        "last_name": "Al-Fayez",
        "email": "reem.alfayez@example.com",
        "company": "Diriyah Gate Development Authority",
        "industries": ["Giga-projects & Smart Cities", "Culture & Heritage"],
        "categories": ["Professional"],
        "interests": "Heritage-led development, cultural tourism, placemaking",
        "phone": "+966 55 666 4411",
        "bio": "Programme manager on a major heritage and tourism development.",
        "linkedin": "https://www.linkedin.com/in/example-reem-alfayez",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Daniel",
        "last_name": "Mercer",
        "email": "daniel.mercer@example.com",
        "company": "Mercer Talent Partners",
        "industries": ["Human Resources & Talent", "Education & Training"],
        "categories": ["Company Owner"],
        "interests": "Cross-border hiring, relocation, early-career pipelines",
        "phone": "+44 7700 900901",
        "bio": "Recruiter specialising in placing UK technical talent into Gulf roles.",
        "linkedin": "https://www.linkedin.com/in/example-daniel-mercer",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Sara",
        "last_name": "Al-Zahrani",
        "email": "sara.alzahrani@example.com",
        "company": "King Abdullah University of Science and Technology",
        "industries": ["Research & Academia", "Water & Desalination"],
        "categories": ["Professional"],
        "interests": "Desalination efficiency, water reuse, research partnerships",
        "phone": "+966 50 555 7788",
        "bio": "Research scientist working on low-energy desalination technologies.",
        "linkedin": "https://www.linkedin.com/in/example-sara-alzahrani",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Michael",
        "last_name": "Chen",
        "email": "michael.chen@example.com",
        "company": "Bracknell Capital",
        "industries": ["Venture Capital & Private Equity", "Fintech"],
        "categories": ["Investor"],
        "interests": "Series A fintech, MENA expansion, portfolio introductions",
        "phone": "+44 7700 900112",
        "bio": "Partner at a London venture fund with a growing MENA mandate.",
        "linkedin": "https://www.linkedin.com/in/example-michael-chen",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Maha",
        "last_name": "Al-Sudairi",
        "email": "maha.alsudairi@example.com",
        "company": "Athar Communications",
        "industries": ["Marketing & Communications", "Film, TV & Media"],
        "categories": ["Company Owner", "Entrepreneur"],
        "interests": "Brand strategy, regional media, content production",
        "phone": "+966 56 888 2200",
        "bio": "Runs a communications agency working with Saudi cultural institutions.",
        "linkedin": "https://www.linkedin.com/in/example-maha-alsudairi",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Oliver",
        "last_name": "Hartley",
        "email": "oliver.hartley@example.com",
        "company": "Hartley Aerospace",
        "industries": ["Aviation & Aerospace", "Defence & Security"],
        "categories": ["Company Owner"],
        "interests": "Offset agreements, GAMI localisation, supply chain qualification",
        "phone": "+44 7700 900223",
        "bio": "Aerospace components manufacturer pursuing Saudi localisation partnerships.",
        "linkedin": "https://www.linkedin.com/in/example-oliver-hartley",
        "membership_tier": "Corporate Membership",
        "active": True,
        "is_searchable": False,
    },
    {
        "first_name": "Tariq",
        "last_name": "Al-Amoudi",
        "email": "tariq.alamoudi@example.com",
        "company": "Jeddah Growth Labs",
        "industries": ["Technology & Software", "Retail & E-commerce"],
        "categories": ["Entrepreneur"],
        "interests": "Marketplace models, consumer tech, seed fundraising",
        "phone": "+966 54 909 1122",
        "bio": "Second-time founder building consumer marketplace products.",
        "linkedin": "https://www.linkedin.com/in/example-tariq-alamoudi",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Isabelle",
        "last_name": "Laurent",
        "email": "isabelle.laurent@example.com",
        "company": "Atelier Laurent",
        "industries": ["Architecture & Design", "Real Estate & Development"],
        "categories": ["Company Owner", "Professional"],
        "interests": "Sustainable design, masterplanning, giga-project commissions",
        "phone": "+44 7700 900334",
        "bio": "Architect working on large-scale mixed-use developments.",
        "linkedin": "https://www.linkedin.com/in/example-isabelle-laurent",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Saad",
        "last_name": "Al-Ghamdi",
        "email": "saad.alghamdi@example.com",
        "company": "Tuwaiq Mining Company",
        "industries": ["Mining & Metals", "Manufacturing & Industrial"],
        "categories": ["Professional"],
        "interests": "Critical minerals, processing capacity, offtake agreements",
        "phone": "+966 53 777 0099",
        "bio": "Operations lead in mineral processing and downstream metals.",
        "linkedin": "https://www.linkedin.com/in/example-saad-alghamdi",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Grace",
        "last_name": "Adeyemi",
        "email": "grace.adeyemi@example.com",
        "company": "Solstice Climate",
        "industries": ["Environment & Sustainability", "Waste & Circular Economy"],
        "categories": ["Entrepreneur", "Company Owner"],
        "interests": "Circular economy, waste-to-value, Saudi Green Initiative",
        "phone": "+44 7700 900445",
        "bio": "Founder of a climate venture working on industrial waste valorisation.",
        "linkedin": "https://www.linkedin.com/in/example-grace-adeyemi",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Hussain",
        "last_name": "Al-Sayed",
        "email": "hussain.alsayed@example.com",
        "company": "London School of Economics",
        "industries": ["Research & Academia", "Banking & Financial Services"],
        "categories": ["Student"],
        "interests": "Development economics, sovereign wealth, graduate roles in finance",
        "phone": "+44 7700 900556",
        "bio": "Master's student in economics, looking for graduate roles across the corridor.",
        "linkedin": "https://www.linkedin.com/in/example-hussain-alsayed",
        "membership_tier": "Basic Membership",
        "active": True,
        "is_searchable": True,
    },
    {
        "first_name": "Amira",
        "last_name": "Kassem",
        "email": "amira.kassem@example.com",
        "company": "Wadi Hospitality Group",
        "industries": ["Tourism & Hospitality", "Food & Beverage"],
        "categories": ["Company Owner", "Entrepreneur"],
        "interests": "Hotel development, F&B concepts, Red Sea tourism",
        "phone": "+966 55 333 6677",
        "bio": "Operates boutique hospitality concepts across the Gulf.",
        "linkedin": "https://www.linkedin.com/in/example-amira-kassem",
        "membership_tier": "Premium Membership",
        "active": True,
        "is_searchable": False,
    },
    # --- Pending admin review: public applications not yet activated ---------------
    {
        "first_name": "Ryan",
        "last_name": "Kowalski",
        "email": "ryan.kowalski@example.com",
        "company": "Northwind Cyber",
        "industries": ["Cybersecurity", "Technology & Software"],
        "categories": ["Professional"],
        "interests": "Critical infrastructure security, NCA compliance, threat intelligence",
        "phone": "+44 7700 900667",
        "bio": "Security engineer focused on operational technology environments.",
        "linkedin": "https://www.linkedin.com/in/example-ryan-kowalski",
        "membership_tier": "Basic Membership",
        "active": False,
        "is_searchable": False,
    },
    {
        "first_name": "Dalia",
        "last_name": "Al-Nasser",
        "email": "dalia.alnasser@example.com",
        "company": "Barakah Social Ventures",
        "industries": ["Non-profit & Social Impact", "Education & Training"],
        "categories": ["Entrepreneur"],
        "interests": "Social enterprise, education access, impact measurement",
        "phone": "+966 50 444 8811",
        "bio": "Builds social enterprise programmes focused on education access.",
        "linkedin": "https://www.linkedin.com/in/example-dalia-alnasser",
        "membership_tier": "Basic Membership",
        "active": False,
        "is_searchable": False,
    },
    {
        "first_name": "Peter",
        "last_name": "Nakamura",
        "email": "peter.nakamura@example.com",
        "company": "Orbital Systems UK",
        "industries": ["Space & Satellite", "Telecommunications"],
        "categories": ["Professional", "Investor"],
        "interests": "Satellite comms, ground infrastructure, space sector partnerships",
        "phone": "+44 7700 900778",
        "bio": "Works in satellite communications, exploring Gulf ground-station projects.",
        "linkedin": "https://www.linkedin.com/in/example-peter-nakamura",
        "membership_tier": "Basic Membership",
        "active": False,
        "is_searchable": False,
    },
]
