"""add blocked_at to members

Revision ID: 2b35a32a8348
Revises: 81697bbf20b2
Create Date: 2026-09-09 14:08:21.884069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b35a32a8348'
down_revision: Union[str, Sequence[str], None] = '81697bbf20b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'blocked_at')
    # ### end Alembic commands ###
