"""add categories to members

Revision ID: 5b246899facb
Revises: 2b35a32a8348
Create Date: 2026-09-09 14:54:15.653240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b246899facb'
down_revision: Union[str, Sequence[str], None] = '2b35a32a8348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('categories', postgresql.ARRAY(sa.String(length=60)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'categories')
    # ### end Alembic commands ###
