"""add connection reports

Revision ID: 5b58b14ecbd1
Revises: d1d5b8daf029
Create Date: 2026-09-30 02:30:19.157005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b58b14ecbd1'
down_revision: Union[str, Sequence[str], None] = 'd1d5b8daf029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_member_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('reported_message', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['connection_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_reports_reported_member_id'), 'connection_reports', ['reported_member_id'], unique=False)
    op.create_index(op.f('ix_connection_reports_request_id'), 'connection_reports', ['request_id'], unique=False)
    op.create_index(op.f('ix_connection_reports_reviewed'), 'connection_reports', ['reviewed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_reports_reviewed'), table_name='connection_reports')
    op.drop_index(op.f('ix_connection_reports_request_id'), table_name='connection_reports')
    op.drop_index(op.f('ix_connection_reports_reported_member_id'), table_name='connection_reports')
    op.drop_table('connection_reports')
    # ### end Alembic commands ###
