"""add connection requests

Revision ID: d1d5b8daf029
Revises: dfb7d05b1279
Create Date: 2026-09-30 02:16:54.348875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d5b8daf029'
down_revision: Union[str, Sequence[str], None] = 'dfb7d05b1279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'recipient_id', name='uq_connection_pair')
    )
    op.create_index(op.f('ix_connection_requests_recipient_id'), 'connection_requests', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_requester_id'), 'connection_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_status'), 'connection_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_requests_status'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_requester_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_recipient_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    # ### end Alembic commands ###
