"""add industries to members

Revision ID: dfb7d05b1279
Revises: 5b246899facb
Create Date: 2026-09-11 20:00:19.121765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfb7d05b1279'
down_revision: Union[str, Sequence[str], None] = '5b246899facb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('industries', postgresql.ARRAY(sa.String(length=120)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'industries')
    # ### end Alembic commands ###
